### PR TITLE
Relax upper version bound for transformer and stm

### PR DESCRIPTION
**Pull request by maoe**

### CODE REVIEW

**Comment by maoe** [comment]
Travis CI [failed](https://travis-ci.org/ekmett/foreign-var/jobs/175920820#L469-L477) with GHC HEAD because Cabal is apparently too old.

**Comment by maoe** [comment]
Any chance of getting this merged?

**Comment by maoe** [comment]
Ping

**Comment by maoe** [comment]
Updated the version bound for stm as well.

**Comment by Fuuzetsu** [comment]
@ekmett I'm happy to co-maintain this if you're too busy.

**Comment by fumieval** [comment]
@ekmett ping?

**Comment by ekmett** [comment]
This has been deprecated in favor of [StateVar](http://hackage.haskell.org/package/StateVar-1.1.1.1/docs/Data-StateVar.html) which was the result of merging my work with the code from the `OpenGL` package by Sven Panne.

I just forgot this package was even here, hence my lower than usual responsiveness to issues filed here.

**Comment by maoe** [comment]
> This has been deprecated in favor of StateVar which was the result of merging my work with the code from the OpenGL package by Sven Panne.

Ah I see, didn't know that. I'll update our code with StateVar then.

**Pull request closed without merging**
